name: shrine
description: Discover how Material Components for Flutter make it easy to differentiate your product and express your brand through design.

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  # flutter_slidable: ^0.6.0
  intl: ^0.17.0
  lottie: ^3.3.1

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2
  url_launcher: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/lottie.json
    - assets/diamond.png
    - assets/0-0.jpeg
    - assets/1-0.jpeg
    - assets/2-0.jpeg
    - assets/3-0.jpeg
    - assets/4-0.jpeg
    - assets/5-0.jpeg
    - assets/6-0.jpeg
    - assets/7-0.jpeg
